[CONTENT REVIEW] 29 - Stranger Things - Atualiza Readme, eslint
betrybe/sd-0x-stranger-things-backend pull request #6
Opened 2020-11-30 14:00 UTC by orlando-messias

[issue](https://github.com/betrybe/course/issues/2343)

2020-12-01 11:28 UTC, nato-re approved these changes
:shipit:

2020-12-01 11:43 UTC, gomesanac commented on README.md
> +deverá ser criada com o seu usuário do github.
```suggestion
#### 8 - Deploy do frontend no Heroku

**IMPORTANTE**: Assim como no backend, a variável de ambiente GITHUB_USER deverá ser criada com o seu usuário do github.
```

2020-12-01 13:45 UTC, LizzardMedeiros requested changes
Está ficando muito bom, mas tente seguir à risca o padrão desse [playbook](https://gist.github.com/LizzardMedeiros/81d758d23e6ce085c8e58c7a5394195d)! Estamos elaborando para que seja aplicado a todos os projetos =)

2020-12-01 13:45 UTC, LizzardMedeiros commented on package.json
> +    "eslint": "^7.10.0",
Tem certeza que essa versão não quebra o avaliador? A versão estável é a 6.8.0. Por favor, confirme isso antes de fazer o merge

2020-12-03 13:11 UTC, roziscoding approved these changes

2020-12-07 11:01 UTC, nato-re commented on package.json
> +    "eslint": "^7.10.0",
Acertado

2020-12-07 11:01 UTC, merged